### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by Fabryz** [mape/connect-assetmanager#13]
Started the server, after few HTTP requests it is shown:

```
Caught exception: TypeError: Cannot read property 'headers' of undefined
TypeError: Cannot read property 'headers' of undefined
    at Request.callback (/var/www/express-boilerplate/node_modules/connect-assetmanager/lib/assetmanager.js:263:37)
    at Request.<anonymous> (/var/www/express-boilerplate/node_modules/connect-assetmanager/node_modules/request/main.js:154:67)
    at Request.emit (events.js:64:17)
    at ClientRequest.<anonymous> (/var/www/express-boilerplate/node_modules/connect-assetmanager/node_modules/request/main.js:151:13)
    at ClientRequest.emit (events.js:64:17)
    at Socket.<anonymous> (http.js:1214:11)
      at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:830:27)
    at EventEmitter._tickCallback (node.js:126:26)
```

Where do I see the configs you were talking about? I did not touch anything other than siteConfig.js

**Comment by thegoleffect** [comment]
If you absolutely need it, I have submitted a Pull Request for this issue:

https://github.com/mape/connect-assetmanager/pull/14

**Comment by thegoleffect** [comment]
Eh, it worked for the first server run but it broke again. I'm still debugging.

**Comment by mape** [comment]
I'm closing this ticket but if you are still experiencing issues please open it again.
