### ISSUE TITLE
document the permissions

### ISSUE THREAD

**Issue by ghost** [mape/connect-assetmanager#43]
Can you add any ACL instructions to the readme?  Under Ubuntu I have to use sudo to run node when I include your module. Otherwise I get this:

/home/spatches/learningprojects/expressAssetTest/node_modules/connect-assetmanager/node_modules/step/lib/step.js:39
        throw arguments[0];
                       ^
Error: watch ENOSPC
    at errnoException (fs.js:806:11)
    at FSWatcher.start (fs.js:837:11)
    at Object.fs.watch (fs.js:861:11)
    at module.exports.generateCache.self (/home/spatches/learningprojects/expressAssetTest/node_modules/connect-assetmanager/lib/assetmanager.js:114:9)
    at Array.forEach (native)
    at module.exports.generateCache.self (/home/spatches/learningprojects/expressAssetTest/node_modules/connect-assetmanager/lib/assetmanager.js:105:17)
    at module.exports.settings.forEach (/home/spatches/learningprojects/expressAssetTest/node_modules/connect-assetmanager/lib/assetmanager.js:32:6)
    at Array.forEach (native)
    at Object.module.exports.settings.forEach (/home/spatches/learningprojects/expressAssetTest/node_modules/connect-assetmanager/lib/assetmanager.js:30:22)
    at Function.module.exports.generateCache.self (/home/spatches/learningprojects/expressAssetTest/node_modules/connect-assetmanager/lib/assetmanager.js:103:12)

**Comment by ghost** [comment]
Solved it. It's not permissions but rather inotify limits. See example here about how to change the default limits: http://monodevelop.com/Inotify_Watches_Limit
